// src/components/Hero.vue
<script setup>
import { computed } from 'vue'

const props = defineProps({
  heroData: {
    type: Object,
    default: () => ({})
  }
})

const defaultData = {
  name: 'Kohaku BlueLeaf',
  subname: 'Shih-Ying Yeh　葉適穎',
  badgeImage: '/assets/images/kohaku-badge.webp',
  avatarImage: '/assets/images/kohaku-bg-full.webp',
  bio: [
    'I am a graduate student doing my master\'s in the Computer Science Department at National Tsing Hua University in Taiwan.',
    'I am interested in improving the performance of Generative AI, focusing on training better models, building efficient and robust systems, and developing useful tools.',
    'I\'m currently working on project: HomeDiffusion. HomeDiffusion seeks to enable pretrained diffusion models on consumer-level hardware. And we already have a usable model: HDM-xut-340M-anime. Which is trained with 1500 GPU hour on 5090.'
  ],
  quote: 'AI art should look like AI, not humans.',
  socials: [
    { icon: 'i-carbon-logo-github', url: 'https://github.com/KohakuBlueleaf', label: 'GitHub' },
    { icon: 'i-carbon-email', url: 'mailto:kohaku@kblueleaf.net', label: 'Email' },
    { icon: 'i-carbon-logo-linkedin', url: 'https://www.linkedin.com/in/適穎-葉-80797327b/', label: 'LinkedIn' },
    { icon: 'i-carbon-logo-x', url: 'https://twitter.com/KBlueleaf', label: 'Twitter' },
    { icon: 'i-carbon-video', url: 'https://space.bilibili.com/507303431', label: 'Bilibili' }
  ]
}

const data = computed(() => ({
  ...defaultData,
  ...props.heroData
}))
</script>

<template>
  <section class="w-full py-12 md:py-20">
    <div class="max-w-6xl mx-auto px-4 md:px-8">
      <div class="flex flex-col md:flex-row gap-8 md:gap-12 items-center">
        <!-- Left side: Text content -->
        <div class="flex-1 order-2 md:order-1">
          <!-- Badge + Name section -->
          <div class="flex items-center gap-4 mb-4">
            <!-- Badge with blur effect -->
            <div class="relative shrink-0">
              <div
                class="absolute inset-0 rounded-2xl"
                :style="{
                  backgroundImage: `url(${data.badgeImage})`,
                  backgroundSize: 'cover',
                  backgroundPosition: 'center',
                  filter: 'blur(15px) contrast(2)'
                }"
              ></div>
              <img
                :src="data.badgeImage"
                alt="Badge"
                class="relative w-32 h-32 rounded-2xl object-cover"
              />
            </div>
            <!-- Name -->
            <div>
              <h1
                class="text-3xl md:text-4xl font-bold bg-gradient-to-r from-purple-400 via-pink-400 to-cyan-400 bg-clip-text text-transparent"
              >
                {{ data.name }}
              </h1>
              <p class="text-xl text-gray-400 mt-1">
                {{ data.subname }}
              </p>
            </div>
          </div>

          <!-- Bio paragraphs -->
          <div class="space-y-4 mt-6">
            <p
              v-for="(paragraph, index) in data.bio"
              :key="index"
              class="text-gray-300 leading-relaxed"
            >
              {{ paragraph }}
            </p>
          </div>

          <!-- Quote -->
          <blockquote class="mt-6 text-gray-200 italic font-bold border-l-4 border-purple-500 pl-4">
            "{{ data.quote }}"
          </blockquote>

          <!-- Social icons -->
          <div class="flex gap-4 mt-8">
            <a
              v-for="social in data.socials"
              :key="social.label"
              :href="social.url"
              :aria-label="social.label"
              target="_blank"
              rel="noopener noreferrer"
              class="text-gray-400 hover:text-white transition-colors duration-200"
            >
              <div :class="[social.icon, 'text-2xl']"></div>
            </a>
          </div>
        </div>

        <!-- Right side: Avatar -->
        <div class="flex-1 order-1 md:order-2 flex justify-center">
          <div class="relative">
            <!-- Blur effect behind avatar -->
            <div
              class="absolute inset-0 rounded-2xl scale-105"
              :style="{
                backgroundImage: `url(${data.avatarImage})`,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                filter: 'blur(15px) contrast(2)'
              }"
            ></div>
            <!-- Avatar image -->
            <img
              :src="data.avatarImage"
              alt="Avatar"
              class="relative rounded-2xl max-w-full w-80 md:w-96 object-cover shadow-2xl"
            />
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// src/partials/Hero.tsx
import { HeroAvatar, HeroSocial, Section } from "astro-boilerplate-components";
import badge from "src/images/kohaku-badge.webp";
import kohaku from "src/images/kohaku-bg-full.webp";

import { GradientText } from "@/components/GradientText";

const cssAvatar = `
#avatar{
  overflow: hidden;
}
#avatar-after {
  content: "";
  position: absolute;
  left: 0;
  right: 0;
  z-index: -1;

  display: block;
  background-image: url(${kohaku.src});
  background-size: cover;
  width: 100%;
  height: 100%;
  filter: blur(15px) contrast(2);
}
`;
const cssBadge = `
#badge{
  overflow: hidden;
  border-radius: 15%;
}
#badge-after {
  content: "";
  position: absolute;
  left: 0;
  right: 0;
  z-index: -1;
  border-radius: 5%;

  display: block;
  background-image: url(${badge.src});
  background-size: cover;
  width: 100%;
  height: 100%;
  filter: blur(15px) contrast(2);
}
`;
const cssDesc = `
p {
  line-height: 1.75rem !important;
}
`;

const Hero = () => (
  <Section>
    <HeroAvatar
      title={
        <>
          <div className="mb-4 flex flex-row items-center">
            <div className="mr-10">
              <style>{cssBadge}</style>
              <div className="relative">
                <div id="badge">
                  <div id="badge-after"></div>
                  <img
                    style={{ height: "8rem" }}
                    src={badge.src}
                    alt="Avatar image"
                    loading="lazy"
                  />
                </div>
              </div>
            </div>
            <div className="flex flex-col">
              <GradientText>Kohaku BlueLeaf</GradientText>
              <span className="text-xl">Shih-Ying, Yeh 　 葉適穎</span>
            </div>
          </div>
        </>
      }
      description={
        <>
          <style>{cssDesc}</style>I am a graduate student doing my master's in the
          Computer Science Department at National Tsing Hua University in
          Taiwan.
          <br></br>
          <br></br> I am interested in improving the performance of Generative
          AI, focusing on training better models, building efficient and robust
          systems, and developing useful tools.
          <br></br>
          <br></br>
          I'm currently working on project: HomeDiffusion.
          <br></br>
          HomeDiffusion seeks to enable pretrained diffusion models on consumer-level hardware.
          And we already have a usable model: HDM-xut-340M-anime.
          Which is trained with 1500 GPU hour on 5090.
          <br></br>
          <br></br>
          <span className="font-bold italic">
            AI art should look like AI, not humans.
          </span>
        </>
      }
      avatar={
        <>
          <style>{cssAvatar}</style>
          <div className="relative mt-7">
            <div id="avatar">
              <div id="avatar-after"></div>
              <img
                style={{ width: "24rem" }}
                src={kohaku.src}
                alt="Avatar image"
                loading="lazy"
              />
            </div>
          </div>
        </>
      }
      socialButtons={
        <>
          <div
            style={{
              filter:
                "invert(45%) sepia(30%) saturate(2000%) hue-rotate(220deg) brightness(90%) contrast(80%)",
            }}
          >
            <div
              style={{ filter: "invert(1) brightness(0)" }}
              className="flex flex-row"
            >
              <a className="mr-3" href="https://github.com/KohakuBlueleaf">
                <HeroSocial
                  src="/assets/images/github-icon.webp"
                  alt="Github icon"
                />
              </a>
              <a className="mr-3" href="mailto:kohaku@kblueleaf.net">
                <HeroSocial src="/assets/images/email.webp" alt="Email icon" />
              </a>
              <a
                className="mr-3"
                href="https://www.linkedin.com/in/適穎-葉-80797327b/"
              >
                <HeroSocial
                  src="/assets/images/linkedin-icon.webp"
                  alt="Linkedin Icon"
                />
              </a>
              <a className="mr-3" href="https://twitter.com/KBlueleaf">
                <HeroSocial
                  src="/assets/images/twitter-bird.webp"
                  alt="Twitter icon"
                />
              </a>
              <a className="mr-3" href="https://space.bilibili.com/507303431">
                <HeroSocial
                  src="/assets/images/bilibili-icon.webp"
                  alt="Bilibili icon"
                />
              </a>
            </div>
          </div>
        </>
      }
    />
  </Section>
);

export { Hero };
